### ISSUE TITLE
Reactor backtrace

### ISSUE THREAD

**Issue by tbodt** [stjepang/smol#125]
When my async program is hanging, I wish the async reactor could dump a stack trace of each blocked future. I think this could be done by calling std::backtrace::Backtrace::capture() when something is registered in the reactor, and providing a method to dump all the saved backtraces for whatever is blocked.

**Comment by stjepang** [comment]
There's a lot of different ways to save the backtrace and dump it but I find it difficult to find one that would work always work well.

My personal wish is for the compiler to implement `Debug` on futures so that by simply printing the future we would get a stacktrace showing where its state machine got stuck. The Go runtime does something like that - it just dumps the state of every goroutine if the whole systems deadlocks.

Since I can't offer anything actionable to do about this right now, I'm gonna close the issue but will keep thinking about this problem...
