### ISSUE TITLE
Errors silenced in Async::<TcpStream>::connect

### ISSUE THREAD

**Issue by Plecra** [stjepang/smol#60]
https://github.com/stjepang/smol/blob/2ccffbbf27043140943ce36bef1c9c9ee55d18a2/src/async_io.rs#L552-L555

Why is it okay to drop any error returned from `Socket::connect`? It could be any of http://man7.org/linux/man-pages/man2/connect.2.html#ERRORS, and a user might be interested in handling this properly

**Comment by stjepang** [comment]
More specifically, we need to ignore the EINPROGRESS error on connect because it just means connection is in progress, which is fine. Unfortunately, `std::io::ErrorKind` has no way to specifically distinguish this error type (I believe it ends up being `ErrorKind::Other` with some kind of message).

I think this is okay because if some other connect error occurs (which is an *actual* error), the following write operation that follows will fail anyway.

**Comment by leo-lb** [comment]
@stjepang I think it would be a great thing to raise against the std!

**Comment by Plecra** [comment]
Is this not [`Error::raw_os_error`](https://doc.rust-lang.org/std/io/struct.Error.html#method.raw_os_error)?

**Comment by stjepang** [comment]
@Plecra Ah I think you're right!

**Comment by hwchen** [comment]
Just looking at how `socket2` did this check, they depend on `libc`. https://github.com/alexcrichton/socket2-rs/blob/master/src/sys/unix.rs#L253

It looks like the raw error code is pretty varied across systems?

And for reference, on windows it looks like you can check `io::ErrorKind::WouldBlock`. https://github.com/alexcrichton/socket2-rs/blob/master/src/sys/windows.rs#L168

**Comment by stjepang** [comment]
Fixed in #90. I have also pushed the same fix to `UnixStream::connect()`.
