### ISSUE TITLE
Creating a TCP socket is not acceptable on Windows

### ISSUE THREAD

**Issue by bill-myers** [stjepang/smol#97]
On Windows, this runtime currently creates a TCP socket on 127.0.0.1 due to its poor IoEvent/Notifier implementation.

This is not acceptable since the existence of such a socket is externally visible and takes up a port on 127.0.0.1 (note that of course there may not even be a local interface with an address!), which is certainly not something that is fine for any Rust async program to do.

Instead, a Windows Event, a pipe or another appropriate mechanism must be used.

**Comment by stjepang** [comment]
I think all we need is to post an IOCP event like here:

https://github.com/tokio-rs/mio/blob/b15fc18458a79ef8a51f73effa92548650f4e5dc/src/sys/windows/waker.rs#L25

But first, `Epoll` needs to implement `AsRawHandle` so that we can get the IOCP handle. I have just submitted a merge request for that:

https://gitlab.com/yorickpeterse/wepoll-binding/-/merge_requests/2

**Comment by stjepang** [comment]
Okay, that PR was merged and `wepoll_binding::Epoll` implements `AsRawHandle` :)

**Comment by stjepang** [comment]
Modern Windows versions support AF_UNIX, which means we can implement `socketpair()` without the current hack occupying TCP ports.

https://internals.rust-lang.org/t/unixstream-on-windows/12305
https://docs.rs/winapi/0.3.8/winapi/um/winsock2/constant.PF_UNIX.html

**Comment by stjepang** [comment]
Go's implementation: https://github.com/golang/go/commit/76c45877c9e72ccc84db787dc08299e0182e0efb
